when:
  - branch: main
    event: push
    path:
      - "src/**"
      - "prisma/**"
      - ".woodpecker/**"
      - "Dockerfile"
  - event: [tag, manual]

clone:
  git:
    image: woodpeckerci/plugin-git
    settings:
      depth: 1

steps:
  dev:
    image: woodpeckerci/plugin-docker-buildx
    settings:
      platforms: linux/amd64,linux/arm64
      repo: codeberg.org/${CI_REPO_OWNER}/koosbot
      registry: codeberg.org
      username: ${CI_REPO_OWNER}
      password:
        from_secret: cb_token
      tag:
        - dev
      cache_from: type=s3,endpoint_url=https://m.noz.one,region=us-east-1,bucket=woodpecker,name=dev
      cache_to: type=s3,endpoint_url=https://m.noz.one,region=us-east-1,bucket=woodpecker,name=dev,mode=max
      aws_region: us-east-1
      aws_access_key_id:
        from_secret: aws_access_key_id
      aws_secret_access_key:
        from_secret: aws_access_key_id
    when:
      branch: main
      event: push
      path:
        - "src/**"
        - "prisma/**"
        - ".woodpecker/**"
        - "Dockerfile"

  publish:
    image: woodpeckerci/plugin-docker-buildx
    settings:
      platforms: linux/amd64,linux/arm64
      repo: codeberg.org/${CI_REPO_OWNER}/koosbot
      registry: codeberg.org
      username: ${CI_REPO_OWNER}
      password:
        from_secret: cb_token
      auto_tag: true
      cache_from: type=s3,endpoint_url=https://m.noz.onz,region=us-east-1,bucket=woodpecker,name=latest
      cache_to: type=s3,endpoint_url=https://m.noz.one,region=us-east-1,bucket=woodpecker,name=latest,mode=max
      aws_region: us-east-1
      aws_access_key_id:
        from_secret: aws_access_key_id
      aws_secret_access_key:
        from_secret: aws_secret_access_key
    when:
      event: tag
